# Generated by Django 3.2.20 on 2023-07-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230724_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
