# Generated by Django 3.2.20 on 2023-08-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
